# Database Configuration
# DEFAULT LOCAL CONFIGURATION
# (Guaranteed to work if your local PostgreSQL is running)
spring.datasource.url=jdbc:postgresql://db.wpsxwizxirrpkgtpkcjd.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=shivampandey.sp

# Explicitly define PostgreSQL so Hibernate doesn't crash while trying to auto-detect a slow-booting database on Render
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
# Let Spring Boot auto-detect the driver and dialect based on the URL!

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.jwtSecret=SchedulixSecretKey
app.jwtExpirationMs=86400000
# src/main/resources/application.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iitian7039@gmail.com
spring.mail.password=ymak cgkk tsvw dpmm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_Sb6hgVlyzEKXdq}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:5uV0IylL7r8csNHlsklhyygj}

# File Upload Configuration
file.upload-dir=./uploads/profile-pics
# Use forward slashes even on Windows for consistency

spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
