
# Database Configuration
# Defaulting to local MySQL. To use Supabase, just pass DB_URL, DB_USERNAME, DB_PASSWORD environment variables!
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/schedulix_db}
spring.datasource.username=postgres
spring.datasource.password=Shivam@123

# Explicitly define PostgreSQL so Hibernate doesn't crash while trying to auto-detect a slow-booting database on Render
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
# Let Spring Boot auto-detect the driver and dialect based on the URL!

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwtSecret=SchedulixSecretKey
app.jwtExpirationMs=86400000
# src/main/resources/application.properties

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=iitian7039@gmail.com
spring.mail.password=ymak cgkk tsvw dpmm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Configuration
file.upload-dir=./uploads/profile-pics
# Use forward slashes even on Windows for consistency

spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
